- name: Install Active Directory Domain Services
  hosts: "{{ windows_ad_server }}"
  gather_facts: false
  vars:
    ansible_user: Administrator
    ansible_password: "jvUo$=9qTK1J7T2ts9F=Q&(792T5NPZl"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5986

  tasks:
    - name: Ensure AD-Domain-Services feature is installed
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: true