- name: Install Active Directory Domain Services
  hosts: "{{ windows_ad_server }}"  
  gather_facts: false
  vars:
    ansible_user: Administrator
    ansible_password: "{{ windows_password }}"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
  become: false

  tasks:
    - name: Ensure AD-Domain-Services feature is installed
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: true
