- name: Create AD Domain
  hosts: "{{ windows_ad_server }}"
  gather_facts: false
  vars:
    ansible_user: Administrator
    ansible_password: "{{ windows_password }}"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    # AD Domain configuration
    dns_domain_name: demo.dns.name.local                      # Your domain name
    domain_netbios_name: DEMO                        # NetBIOS name
    ad_safe_mode_pass: 'SuperSecretSafeModePW1!'     # Directory Services Restore Mode password. Use Ansible Vault for this in production!
    install_dns: true
  become: false
 
  tasks:
    - name: Promote domain controller and create new domain
      ansible.windows.win_domain:
        dns_domain_name: "{{ dns_domain_name }}"
        domain_netbios_name: "{{ domain_netbios_name }}"
        safe_mode_password: "{{ ad_safe_mode_pass }}"
        install_dns: "{{ install_dns }}"
      register: domain_result

    - name: Show result of domain creation
      debug:
        var: domain_result