- name: Create AD groups and users under "Users" container
  hosts: windows
  gather_facts: false
  vars:
    ansible_user: Administrator
    ansible_password: "jvUo$=9qTK1J7T2ts9F=Q&(792T5NPZl"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985

    ad_users_container: "CN=Users,DC=demo,DC=dns,DC=name,DC=local"
    ad_groups:
      - development
      - operations
    ad_users:
      - name: Abby
        password: "Password1!"
        groups: [development]
      - name: Bob
        password: "Password1!"
        groups: [development]
      - name: Candy
        password: "Password1!"
        groups: [operations]
      - name: Dog
        password: "Password1!"
        groups: [operations]

  tasks:
    - name: Ensure AD groups exist in the Users container
      microsoft.ad.group:
        name: "{{ item }}"
        scope: global
        path: "{{ ad_users_container }}"
        state: present
      loop: "{{ ad_groups }}"

    - name: Ensure AD users exist and are in their correct groups
      microsoft.ad.user:
        identity: "{{ item.name }}"
        password: "{{ item.password }}"
        path: "{{ ad_users_container }}"
        state: present
        groups:
          set: "{{ item.groups }}"
        update_password: always
        password_never_expires: true
        user_cannot_change_password: false
        enabled: true
      loop: "{{ ad_users }}"